version: "3.8"
name: "kecbazar"
services:
  db:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kecbazar_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    

  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/amd64
    ports:
      - "8080:80"
    depends_on:
      - db

  php:
    build: .
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - phpmyadmin